services:
  ollama:
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    volumes:
      - ./.data/ollama:/root/.ollama
    image: ollama/ollama:0.4.2
  searxng:
    image: searxng/searxng:2024.11.17-10d3af84b
    ports:
      - "8080:8080"
    volumes:
      - ./.data/searxng:/etc/searxng
  open-webui:
    ports:
      - 3000:8080
    volumes:
      - ./.data/open-webui:/app/backend/data
    image: ghcr.io/open-webui/open-webui:0.4.2
    environment:
      WEBUI_AUTH: False 
      OLLAMA_BASE_URL: http://ollama:11434
      ENABLE_RAG_WEB_SEARCH: True
      RAG_WEB_SEARCH_ENGINE: "searxng"
      RAG_WEB_SEARCH_RESULT_COUNT: 3
      RAG_WEB_SEARCH_CONCURRENT_REQUESTS: 10
      SEARXNG_QUERY_URL: "http://localhost:8080/search?q=<query>"
    depends_on:
      - ollama
      - searxng